## **Introduction**

Welcome to this comprehensive guide on NumPy, the essential Python library for numerical computing. Whether you're a data scientist, machine learning enthusiast, or simply want to work with numerical data efficiently, NumPy is a foundational tool you'll want in your toolkit. In this guide, we'll cover the fundamental concepts and techniques, from creating arrays to advanced data manipulation, to help you harness the full potential of NumPy for your data-driven tasks.

## Import Numpy
The code imports the numpy library and assigns it an alias 'np'. Numpy is a fundamental package for scientific computing with Python. It contains among other things:
- A powerful N-dimensional array object
- Sophisticated (broadcasting) functions
- Tools for integrating C/C++ and Fortran code
- Useful linear algebra, Fourier transform, and random number capabilities

In [1]:
# Importing the numpy library and aliasing it as np
# Numpy is a library in python that provides support to work with arrays,
# and also provides a collection of mathematical functions to operate on these arrays.

import numpy as np 


## Creating an One-dimentional Array
The variable a is assigned a numpy array containing the elements 1, 2, and 3. Numpy arrays are homogeneous in nature, i.e., they contain elements of the same data type. In this case, the elements are integers.

In [2]:
# Creating a numpy array 'a' with elements 1, 2, and 3
a = np.array([1,2,3])

# Displaying the type of object 'a' to confirm that it is a numpy array
type(a)

numpy.ndarray

In [3]:
# Displaying the shape of the numpy array 'a'
# The shape is a tuple representing the dimensionality of the array.
a.shape 

(3,)

In [4]:
# Displaying the number of dimensions of the numpy array 'a' using the 'ndim' attribute
a.ndim 

1

## Two-dimentional Array
The code initializes a two-dimensional numpy array b. The array b is constructed using two lists [1,2,3] and [2,3,4], which act as rows in the two-dimensional array.

In [5]:
# Creating a two-dimensional numpy array 'b'
# The array 'b' consists of two lists [1,2,3] and [2,3,4] as its elements (rows)

b = np.array([[1,2,3], [2,3,4]])

In [6]:
type(b)

numpy.ndarray

In [7]:
# Displaying the shape and number of dimensions of the two-dimensional numpy array 'b'
# 'b.shape' returns a tuple representing the dimensionality (rows, columns) of the array 'b'
# 'b.ndim' returns the number of dimensions of the array 'b'
b.shape, b.ndim

((2, 3), 2)

## Three-dimentional Array
The code initializes two three-dimensional numpy arrays, c and d.
- The array c is created with one set of square brackets surrounding the matrices, making it a three-dimensional array with one element.
- It consists of a single 3x3 matrix as its element.
- The array d is created with two 3x3 matrices, making it a three-dimensional array with two elements.
- Each element in d is a 3x3 matrix.

In [8]:
# Creating a three-dimensional numpy array 'c'
# The array 'c' consists of a single matrix [[1,2,3], [2,3,4], [3,4,5]] as its element

c = np.array([[
        [1,2,3],
        [2,3,4],
        [3,4,5]
            ]])

# Creating another three-dimensional numpy array 'd'
# The array 'd' consists of two matrices, each [[1,2,3], [2,3,4], [3,4,5]], as its elements

d = np.array([
    [[1,2,3],[2,3,4],[3,4,5]],
    [[1,2,3],[2,3,4],[3,4,5]]
    ])

In [9]:
# Printing the shape of the three-dimensional numpy array 'c'
# This will output a tuple representing the shape (dimensionality) of array 'c'
print(f"The shape of array 'c' is: {c.shape}")

# Printing the shape of the three-dimensional numpy array 'd'
# This will output a tuple representing the shape (dimensionality) of array 'd'
print(f"The shape of array 'd' is: {d.shape}")

The shape of array 'c' is: (1, 3, 3)
The shape of array 'd' is: (2, 3, 3)


In [10]:
# Printing the data types of the elements in the numpy arrays 'a', 'b', and 'c'
# The '.dtype' attribute returns the data type of the elements in the arrays

print(f"The data type of elements in array 'a' is: {a.dtype}")
print(f"The data type of elements in array 'b' is: {b.dtype}")
print(f"The data type of elements in array 'c' is: {c.dtype}")

The data type of elements in array 'a' is: int64
The data type of elements in array 'b' is: int64
The data type of elements in array 'c' is: int64


In [11]:
# Printing the total number of elements in the numpy arrays 'a', 'b', 'c', and 'd'
# The '.size' attribute returns the total number of elements in the array

print(f"The total number of elements in array 'a' is: {a.size}")
print(f"The total number of elements in array 'b' is: {b.size}")
print(f"The total number of elements in array 'c' is: {c.size}")
print(f"The total number of elements in array 'd' is: {d.size}")

The total number of elements in array 'a' is: 3
The total number of elements in array 'b' is: 6
The total number of elements in array 'c' is: 9
The total number of elements in array 'd' is: 18


In [12]:
# Printing the total bytes consumed by the numpy arrays 'a', 'b', 'c', and 'd'
# The '.nbytes' attribute returns the total bytes consumed by the array's elements

print(f"The total bytes consumed by array 'a' is: {a.nbytes} bytes")
print(f"The total bytes consumed by array 'b' is: {b.nbytes} bytes")
print(f"The total bytes consumed by array 'c' is: {c.nbytes} bytes")
print(f"The total bytes consumed by array 'd' is: {d.nbytes} bytes")


The total bytes consumed by array 'a' is: 24 bytes
The total bytes consumed by array 'b' is: 48 bytes
The total bytes consumed by array 'c' is: 72 bytes
The total bytes consumed by array 'd' is: 144 bytes


## Array Creation
In this code snippet, a numpy array named myarray is created and initialized with the elements [1,2,3]. Additionally, the data type of the elements within the array is explicitly specified as integer (int) using the dtype parameter.

In [13]:
# Creating a numpy array 'myarray' with specified data type
# The array is initialized with elements [1,2,3] and the data type is set as integer ('int')

myarray = np.array([1,2,3], dtype='int')

In [14]:
# Creating a 3x3 numpy array 'zeroArray' filled with zeros
# The dtype parameter is specified as 'float', setting the data type of the elements to floating-point numbers

zeroArray = np.zeros((3,3), dtype='float')
zeroArray

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# Creating a 2x3 numpy array 'oneArray' filled with ones
# The dtype parameter is specified as 'float', setting the data type of the elements to floating-point numbers

oneArray = np.ones((2,3), dtype='float')
oneArray

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# Creating a 2x3 numpy array 'fullArray' filled with the value 5
# The 'np.full()' function is used with specified shape and fill value

fullArray = np.full((2,3), 5)
fullArray 

array([[5, 5, 5],
       [5, 5, 5]])

## Identity Matrix
An identity matrix, also known as a unit matrix, is a square matrix in which all diagonal elements are equal to 1 and all other elements are 0.

In [17]:
# Creating a 3x3 identity matrix 'identity1' with integer data type
# The 'np.identity()' function is used, specifying the size and the data type of the elements

identity1 = np.identity(3, dtype='int')
identity1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [18]:
# Creating a 2x2 identity matrix 'identity2' with integer data type
# The 'np.identity()' function is used, specifying the size and the data type of the elements

identity2 = np.identity(2, dtype='int')
print(identity2)

[[1 0]
 [0 1]]


In [19]:
# Creating a 3x3 identity matrix 'eye1' using the 'np.eye()' function
# The function is called with parameters defining the number of rows and columns

eye1 = np.eye(3, 3)
eye1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
eye2 = np.eye(3,3,1)
eye2

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [21]:
# Creating a numpy array 'arange' using the 'np.arange()' function
# The function is called with parameters defining the start, stop, and step values

arange = np.arange(1, 10, 2)
arange

array([1, 3, 5, 7, 9])

In [22]:
# Creating a numpy array 'linspace1' using the 'np.linspace()' function
# The function is called with parameters defining the start value, end value, and number of values to generate
# An additional parameter is used to set the data type of the elements to integers

linspace1 = np.linspace(1, 55, 10, dtype='int')
print(linspace1)

[ 1  7 13 19 25 31 37 43 49 55]


In [23]:
# Getting the shape of the 'linspace1' array and printing it
# The shape will indicate the dimensions of the array

shape_of_linspace1 = linspace1.shape
print(f"The shape of linspace1 array is: {shape_of_linspace1}")

The shape of linspace1 array is: (10,)


In [24]:
# Getting the number of dimensions of the 'linspace1' array and printing it
# The number of dimensions indicates how many indexes are needed to access an element

num_dimensions_linspace1 = linspace1.ndim
print(f"The number of dimensions of linspace1 array is: {num_dimensions_linspace1}")

The number of dimensions of linspace1 array is: 1


In [25]:
# Creating an empty numpy array 'empty1' with specified shape (1, n), where n is 3
# The 'np.empty()' function returns a new array without initializing the elements to any particular values

n = 3  # Defining the value of n
empty1 = np.empty((1, n))  # Creating an empty array with shape (1, n)
print(empty1)  # Printing the created empty array to inspect its content

[[1. 1. 1.]]


In [26]:
for i in range(n):
    empty1[:,i] = i
empty1

array([[0., 1., 2.]])

## Array Indexing & Slicing
Array indexing and slicing are fundamental operations to access and manipulate array data. Below are some examples with explanations and documentation for different cases of array indexing and slicing.

**Example 1:Basic Indexing**

In the code snippet above, a one-dimensional numpy array array1 is created. An individual element of the array is accessed using its index. Since indexing starts from 0, array1[2] accesses the third element of the array.

In [27]:
import numpy as np

# Creating a sample array
array1 = np.array([1, 2, 3, 4, 5])

# Accessing an element using indexing
element = array1[2]  # This will access the third element of the array (Indexing starts from 0)
print(f"Accessed element: {element}")

Accessed element: 3


**Example 2: Basic Slicing**

A subarray is extracted from array1 by specifying the start and end indices. The slice array1[1:4] includes elements from index 1 up to, but not including, index 4, resulting in a subarray.

In [28]:
# Slicing array to get a subarray
subarray = array1[1:4]  # This will retrieve elements from index 1 to index 3
print(f"Subarray: {subarray}")

Subarray: [2 3 4]


**Example 3: Multidimensional Array Indexing and Slicing**

A two-dimensional array array2 is created, and individual elements are accessed using row and column indices. Slicing is used to extract specific rows and columns, yielding a subarray.

In [29]:
# Creating a multidimensional array
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing an element
element = array2[1, 2]  # Accessing element from the second row and third column
print(f"Accessed element: {element}")

# Slicing to get a subarray
subarray = array2[0:2, 1:3]  # Getting a 2x2 subarray from the first two rows and last two columns
print(f"Subarray:\n{subarray}")

Accessed element: 6
Subarray:
[[2 3]
 [5 6]]


## Manipulation of Array
Here are some common manipulations to perform on numpy arrays such as reshaping, transposing, concatenating, and splitting.

**Example 1: Reshaping an Array**

In this code, the numpy array array1 is reshaped into a 2x3 matrix using the reshape() method, resulting in reshaped_array.

In [30]:
import numpy as np

# Creating a sample array
array1 = np.array([1, 2, 3, 4, 5, 6])

# Reshaping the array
reshaped_array = array1.reshape(2, 3)
print(f"Reshaped array:\n{reshaped_array}")

Reshaped array:
[[1 2 3]
 [4 5 6]]


**Example 2: Transposing an Array**

The reshaped_array is transposed, meaning its rows become columns and vice versa, resulting in transposed_array.

In [31]:
# Transposing the reshaped array
transposed_array = reshaped_array.T
print(f"Transposed array:\n{transposed_array}")

Transposed array:
[[1 4]
 [2 5]
 [3 6]]


**Example 3: Concatenating Arrays**

Two arrays, array2 and array3, are concatenated along the first axis (vertically), resulting in a new array, concatenated_array.

In [32]:
# Creating two arrays to concatenate
array2 = np.array([[1, 2], [3, 4]])
array3 = np.array([[5, 6]])

# Concatenating along the first axis (vertically)
concatenated_array = np.concatenate((array2, array3), axis=0)
print(f"Concatenated array:\n{concatenated_array}")

Concatenated array:
[[1 2]
 [3 4]
 [5 6]]


**Example 4: Splitting an Array**

The concatenated_array is split into two arrays along the first axis (vertically), resulting in a list of new arrays, split_arrays.

In [33]:
# Splitting the concatenated array into two
# Using np.array_split() to handle unequal splitting
split_arrays = np.array_split(concatenated_array, 2, axis=0)
print(f"Split arrays:\n{split_arrays}")

Split arrays:
[array([[1, 2],
       [3, 4]]), array([[5, 6]])]


## Resize an Array, resize()

The resize() function in numpy can be used to change the shape of an array, and it may also modify the array itself. 

In [34]:
# Creating a sample array
array1 = np.array([1, 2, 3, 4])

# Resizing the array to shape (2, 3)
resized_array = np.resize(array1, (2, 3))

print(f"Original array:\n{array1}")
print(f"Resized array:\n{resized_array}")

Original array:
[1 2 3 4]
Resized array:
[[1 2 3]
 [4 1 2]]


## Flattened an Array by ravel()
The ravel() function is used to return a flattened array. 

In [35]:
# Creating a two-dimensional array
array2D = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Original array:\n{array2D}")

# Using the ravel() function to flatten the array
flattened_array = array2D.ravel()
print(f"Flattened array:\n{flattened_array}")

Original array:
[[1 2 3]
 [4 5 6]]
Flattened array:
[1 2 3 4 5 6]


### Flatten()
The flatten() method in numpy is utilized to return a copy of the array collapsed into one dimension. 

In [36]:
# Creating a two-dimensional array
array2D = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Original array:\n{array2D}")

# Using the flatten() method to flatten the array
flattened_array = array2D.flatten()
print(f"Flattened array:\n{flattened_array}")

Original array:
[[1 2 3]
 [4 5 6]]
Flattened array:
[1 2 3 4 5 6]


## Defining an Array Shape
Defining an array shape means setting the dimensions (number of rows and columns, for example) of the array. It could be done during the creation of the array or later, by reshaping the array without changing its data. Below are examples:

**Example 1: Defining Shape During Array Creation**

In [37]:
# Creating a two-dimensional array with a specific shape
array_with_shape = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Array with defined shape:\n{array_with_shape}")

Array with defined shape:
[[1 2 3]
 [4 5 6]]


**Example 2: Reshaping an Existing Array**

In [38]:
# Reshaping the array to a different shape
reshaped_array = array_with_shape.reshape((3, 2))
print(f"Reshaped array:\n{reshaped_array}")

Reshaped array:
[[1 2]
 [3 4]
 [5 6]]


## Stacking
Stacking in NumPy refers to the action of joining a sequence of arrays along a new axis. You can perform stacking horizontally (hstack), vertically (vstack), or along a specified axis (stack). Below are examples of these different types of stacking

**Example: Horizontal and Vertical Stacking**

- **Horizontal Stacking (hstack):** Joins two or more arrays horizontally, meaning the arrays are joined column-wise.
- **Vertical Stacking (vstack):** Joins two or more arrays vertically, meaning the arrays are joined row-wise.

In [39]:
# Creating two arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Horizontal Stacking
hstacked_array = np.hstack((array1, array2))
print(f"Horizontally Stacked Arrays:\n{hstacked_array}")

# Vertical Stacking
vstacked_array = np.vstack((array1, array2))
print(f"Vertically Stacked Arrays:\n{vstacked_array}")


Horizontally Stacked Arrays:
[[1 2 5 6]
 [3 4 7 8]]
Vertically Stacked Arrays:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**Example: Stacking Along a Specified Axis**

This allows you to specify an axis to stack along. For instance, stacking along axis=0 will stack arrays in a layer-wise fashion.

In [40]:
# Stacking along a new axis
stacked_array = np.stack((array1, array2), axis=0)
print(f"Stacked Arrays along a new axis:\n{stacked_array}")

Stacked Arrays along a new axis:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Example: Column Stackt**

The column_stack() function in NumPy is used to stack one-dimensional arrays as columns into a two-dimensional array. It is equivalent to numpy.hstack() but makes most sense for stacking one-dimensional arrays and is more convenient for that use case.

In [41]:
# Creating two one-dimensional arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Using the column_stack() function to stack arrays as columns
stacked_array = np.column_stack((array1, array2))
print(f"Stacked array using column_stack():\n{stacked_array}")

Stacked array using column_stack():
[[1 4]
 [2 5]
 [3 6]]


**Example: Depth Stack**

Depth stacking in NumPy can be accomplished using the np.dstack() function. The np.dstack() function stacks arrays in sequence along the third axis (depth). This means that it takes each slice from the input arrays and stacks them along a new third axis to form a single array. 

In [42]:
# Creating two two-dimensional arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Using the dstack() function to stack arrays along the third axis (depth)
depth_stacked_array = np.dstack((array1, array2))
print(f"Depth Stacked Array:\n{depth_stacked_array}")

Depth Stacked Array:
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


## Iterating Arrays
Iterating over arrays in NumPy can be performed in various ways, depending on the task at hand. You might iterate element-wise, row-wise, or using more complex iteration patterns. Here are some examples:

**Example 1: Element-wise Iteration**

Using np.nditer(), you can iterate over each element of the array, regardless of the array's shape or number of dimensions.

In [43]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Iterating over each element of the array
for element in np.nditer(array):
    print(element)

1
2
3
4
5
6


**Example 2: Row-wise Iteration**

By default, iterating directly over a NumPy array will give you each row (or the first axis) as a separate array.

In [44]:
# Iterating over each row of the array
for row in array:
    print(row)

[1 2 3]
[4 5 6]


**Example 3: Iterating with Index**

np.ndenumerate() function returns pairs containing the index and the value of each element. It’s useful when the position information is necessary.

In [45]:
# Iterating over each element with index using ndenumerate
for index, element in np.ndenumerate(array):
    print(f"Index {index} has element {element}")

Index (0, 0) has element 1
Index (0, 1) has element 2
Index (0, 2) has element 3
Index (1, 0) has element 4
Index (1, 1) has element 5
Index (1, 2) has element 6


## Splitting NumPy Arrays

Splitting a NumPy array involves breaking it into multiple arrays along a specified axis. This can be done using various functions such as np.split(), np.hsplit(), and np.vsplit().

**Example 1: Using np.split()**

Using np.split(): Generic function where the axis along which the array will be split is specified.

In [46]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Splitting the array into two along the vertical axis (axis=0)
split_arrays = np.split(array, 3, axis=0)
print(f"Splitted arrays:\n{split_arrays}")

Splitted arrays:
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


**Example 2: Using np.hsplit()**

Using np.hsplit(): Splits an array into multiple sub-arrays horizontally (column-wise).

In [47]:
# Horizontally splitting the array into three equal parts
split_arrays = np.hsplit(array, 3)
print(f"Horizontally splitted arrays:\n{split_arrays}")

Horizontally splitted arrays:
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


**Example 3: Using np.vsplit()**

Using np.vsplit(): Splits an array into multiple sub-arrays vertically (row-wise).

In [48]:
# Vertically splitting the array into three equal parts
split_arrays = np.vsplit(array, 3)
print(f"Vertically splitted arrays:\n{split_arrays}")

Vertically splitted arrays:
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


## Searching Arrays
Searching within a NumPy array can be accomplished using various functions like np.where(), np.argmax(), np.argmin(), and np.nonzero(). These functions help in finding elements, indices, or positions based on specified conditions or criteria.

**Example 1: Using np.where()**

Returns indices where a specified condition is met. It is a versatile function that can also be used to return elements based on conditions.

In [49]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Finding the indices where value is greater than 5
indices = np.where(array > 5)
print(f"Indices where value > 5: {indices}")


Indices where value > 5: (array([1, 2, 2, 2]), array([2, 0, 1, 2]))


**Example 2: Using np.argmax() and np.argmin()**

These functions return the index of the maximum and minimum elements in the array, respectively.

In [50]:
# Finding the index of the maximum value in the array
max_index = np.argmax(array)
print(f"Index of maximum value: {max_index}")

# Finding the index of the minimum value in the array
min_index = np.argmin(array)
print(f"Index of minimum value: {min_index}")

Index of maximum value: 8
Index of minimum value: 0


**Example 3: Using np.nonzero()**

Returns the indices of non-zero elements in the input array.

In [51]:
# Finding the indices of non-zero elements in the array
nonzero_indices = np.nonzero(array)
print(f"Indices of non-zero elements: {nonzero_indices}")

Indices of non-zero elements: (array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))


## Sorting Arrays
Sorting arrays in NumPy is a common operation that can be performed using various functions like np.sort(), np.argsort(), and in-place sorting using the array method array.sort()

**Example 1: Using np.sort()**

Returns a sorted copy of an array. By default, it sorts the elements in ascending order along the specified axis.

In [52]:
array = np.array([3, 1, 2, 4])

# Sorting the array
sorted_array = np.sort(array)
print(f"Sorted array: {sorted_array}")

Sorted array: [1 2 3 4]


**Example 2: Using np.argsort()**

 Returns the indices that would sort an array. Useful when you want to sort one array based on the values in another.

In [53]:
# Getting the indices that would sort the array
sort_indices = np.argsort(array)
print(f"Indices for sorted array: {sort_indices}")

Indices for sorted array: [1 2 0 3]


**Example 3: In-place Sorting**

The array method array.sort() sorts the array in-place, meaning that the array content is sorted without maintaining the original array.

In [54]:
# Sorting the array in-place
array.sort()
print(f"In-place sorted array: {array}")

In-place sorted array: [1 2 3 4]


## Filtering Arrays
Filtering arrays is a technique used to select and manipulate array elements based on certain conditions or criteria. In NumPy, filtering can be done using boolean indexing, np.where(), or other conditional expressions. 

**Example 1: Boolean Indexing**

**Boolean Indexing:** A boolean array is created based on a condition. This boolean array can be used to index the original array, resulting in an array of elements where the condition is true.

In [55]:
array = np.array([1, 2, 3, 4, 5])

# Creating a boolean array based on a condition
bool_array = array > 3
print(f"Boolean array: {bool_array}")

# Using the boolean array to filter elements
filtered_array = array[bool_array]
print(f"Filtered array: {filtered_array}")

Boolean array: [False False False  True  True]
Filtered array: [4 5]


**Example 2: Using np.where()**

This function returns the indices where a condition is true. These indices can be used to filter elements from the original array.

In [56]:
# Finding indices where a condition is true, and using them to filter elements
indices = np.where(array > 3)
filtered_array = array[indices]
print(f"Filtered array using np.where(): {filtered_array}")

Filtered array using np.where(): [4 5]


**More Example of Filtering**

This code snippet is a demonstration of boolean indexing in NumPy. An array arr is created with four integer elements. A boolean array x is manually created, containing True and False values. This boolean array is used to index the original array arr, resulting in a new array newarr that contains the elements of arr where the corresponding value in x is True.

In [57]:
arr = np.array([41, 42, 43, 44])  # Creating a numpy array

# Defining a boolean array manually
x = [True, False, True, False]  

# Filtering the array 'arr' using the boolean array 'x'
newarr = arr[x]  

print(newarr)  # Printing the filtered array


[41 43]


## Create a filter array that will return only values higher than 42

This code snippet illustrates how to manually create a filter (boolean array) to select specific elements from a NumPy array based on a condition. In this case, the condition is whether the element is greater than 42.

In [58]:
arr = np.array([42, 46, 51, 55])  # Creating a numpy array

filter_arr = []  # Creating an empty list to hold boolean values

# Iterating over each element in 'arr'
for element in arr:
    # Applying the condition to each element
    if element > 42:
        filter_arr.append(True)  # If the condition is met, append True
    else:
        filter_arr.append(False)  # If the condition is not met, append False

# Creating a new array by filtering 'arr' using 'filter_arr'
newarr = arr[filter_arr]  

print(filter_arr)  # Printing the boolean array
print(newarr)  # Printing the filtered array

[False, True, True, True]
[46 51 55]


## **Closing Thoughts**

In this document, we've explored fundamental concepts and techniques for working with arrays in NumPy, a powerful library for numerical computations in Python. From creating arrays to filtering and manipulating data, NumPy offers a versatile toolbox for data scientists, researchers, and engineers.

As you continue your journey in data analysis, machine learning, or any field where numerical data plays a crucial role, mastering NumPy will be an invaluable asset. The ability to efficiently process and manipulate data is at the heart of many data-driven endeavors, and NumPy provides the tools to make it happen.