# Numpy ufunc

### What are ufuncs?
ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

### Why use ufuncs?
ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

ufuncs also take additional arguments, like:

where: boolean array or condition defining where the operations should take place.

dtype: defining the return type of elements.

out: output array where the return value should be copied.

### What is Vectorization?
Converting iterative statements into a vector based operation is called vectorization.
It is faster as modern CPUs are optimized for such operations.

In [1]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [4]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [15]:
def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [16]:
#Use an if statement to check if the function is a ufunc or not:
if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


### Simple Arithmetic

In [17]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [18]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


### Rounding Decimals
There are primarily five ways of rounding off decimals in NumPy:

- truncation
- fix
- rounding
- floor
- ceil

In [19]:
#Truncation
import numpy as np

arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [21]:
#Fix
arr = np.fix([-3.1666, 3.6667])

print(arr)

[-3.  3.]


#### Rounding
- The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.
- E.g. round off to 1 decimal point, 3.16666 is 3.2

In [23]:
arr = np.around(3.1666, 2)

print(arr)

3.17


#### Floor
- The floor() function rounds off decimal to nearest lower integer.
- E.g. floor of 3.166 is 3.

In [24]:
arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


#### Ceil
- The ceil() function rounds off decimal to nearest upper integer.
- E.g. ceil of 3.166 is 4.

In [25]:
arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


## NumPy Logs
NumPy provides functions to perform log at the base 2, e and 10.

We will also explore how we can take log for any base by creating a custom ufunc.

All of the log functions will place -inf or inf in the elements if the log can not be computed.

### Log at Base 2
Use the log2() function to perform log at the base 2.

In [26]:
arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


### Log at Base 10
Use the log10() function to perform log at the base 10.

In [27]:
arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


### Natural Log, or Log at Base e
Use the log() function to perform log at the base e.

In [28]:
arr = np.arange(1, 10)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


### Log at Any Base
NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt function math.log() with two input parameters and one output parameter:

In [29]:
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052


## NumPy Summations
What is the difference between summation and addition?
Addition is done between two arguments whereas summation happens over n elements.

In [33]:
#Addition
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [34]:
#Summation
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


### Summation Over an Axis
If you specify axis=1, NumPy will sum the numbers in each array.

In [35]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


### Cummulative Sum
Cummulative sum means partially adding the elements in array.

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

Perfom partial sum with the cumsum() function.

In [43]:
arr = np.array([1, 2, 3])
newarr = np.cumsum(arr)
print(newarr)

[1 3 6]


## NumPy Products
To find the product of the elements in an array, use the prod() function.

In [42]:
#Find the product of the elements of this array:
#Returns: 24 because 1*2*3*4 = 24

arr = np.array([1, 2, 3, 4])
x = np.prod(arr)
print(x)

24


### Product Over an Axis
If you specify axis=1, NumPy will return the product of each array.
Perform summation in the following array over 1st axis:

In [46]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


### Cummulative Product
Cummulative product means taking the product partially.

E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]

Perfom partial sum with the cumprod() function.

In [47]:
#Take cummulative product of all elements for following array:
arr = np.array([5, 6, 7, 8])
newarr = np.cumprod(arr)
print(newarr)

[   5   30  210 1680]


## NumPy Differences
A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.

In [50]:
#Compute discrete difference of the following array:
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)

#Returns: [5 10 -20] because 15-10=5, 25-15=10, and 5-25=-20

[  5  10 -20]


We can perform this operation repeatedly by giving parameter n.

E.g. for [1, 2, 3, 4], the discrete difference with n = 2 would be [2-1, 3-2, 4-3] = [1, 1, 1] , then, since n=2, we will do it once more, with the new result: [1-1, 1-1] = [0, 0]
Example

In [52]:
#Compute discrete difference of the following array twice:

arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr, n=2)
print(newarr)

[  5 -30]


## NumPy LCM Lowest Common Multiple
The Lowest Common Multiple is the smallest number that is a common multiple of two numbers.

In [53]:
#Find the LCM of the following two numbers:
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


### Finding LCM in Arrays
To find the Lowest Common Multiple of all values in an array, you can use the reduce() method.
The reduce() method will use the ufunc, in this case the lcm() function, on each element, and reduce the array by one dimension.

In [56]:
#Find the LCM of the values of the following array:

arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print(x)

18


In [62]:
#Find the LCM of all values of an array where the array contains all integers from 1 to 10:

arr = np.arange(1, 11)
print("Our Array is: {}".format(arr))
x = np.lcm.reduce(arr)

print("Answer is: {}".format(x))

Our Array is: [ 1  2  3  4  5  6  7  8  9 10]
Answer is: 2520


## NumPy GCD Greatest Common Denominator
The GCD (Greatest Common Denominator), also known as HCF (Highest Common Factor) is the biggest number that is a common factor of both of the numbers.

In [65]:
#Find the HCF of the following two numbers:

X = 6
Y = 9

HCF = np.gcd(X, Y)

print("Highest Common Factor of X & Y is: {}".format(HCF))

#Returns: 3 because that is the highest number both numbers can be divided by (6/3=2 and 9/3=3).

Highest Common Factor of X & Y is: 3


### Finding GCD in Arrays
To find the Highest Common Factor of all values in an array, you can use the reduce() method.

The reduce() method will use the ufunc, in this case the gcd() function, on each element, and reduce the array by one dimension.

In [66]:
#Find the GCD for all of the numbers in the following array:

arr = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(arr)

print(x)

4


## NumPy Trigonometric Functions
NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.

In [68]:
#Find sine value of PI/2:

x = np.sin(np.pi/2)
print(x)

1.0


In [71]:
#Find sine values for all of the values in arr:

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


### Convert Degrees Into Radians
By default all of the trigonometric functions take radians as parameters but we can convert radians to degrees and vice versa as well in NumPy.

__Note:__ radians values are pi/180 * degree_values.

In [73]:
#Convert all of the values in following array arr to radians:

arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


### Radians to Degrees

In [74]:
#Convert all of the values in following array arr to degrees:

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


### Finding Angles
Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

In [75]:
#Find the angle of 1.0:

x = np.arcsin(1.0)
print(x)

1.5707963267948966


### Angles of Each Value in Arrays

In [76]:
#Find the angle for all of the sine values in the array

arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


### Hypotenues
Finding hypotenues using pythagoras theorem in NumPy.

NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.

In [77]:
#Find the hypotenues for 4 base and 3 perpendicular:

import numpy as np

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0


## NumPy Hyperbolic Functions
NumPy provides the ufuncs sinh(), cosh() and tanh() that take values in radians and produce the corresponding sinh, cosh and tanh values..

In [78]:
#Find sinh value of PI/2:

x = np.sinh(np.pi/2)
print(x)

2.3012989023072947


In [80]:
#Find cosh values for all of the values in arr:

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.cosh(arr)

print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


## NumPy Set Operations
A set in mathematics is a collection of unique elements.

Sets are used for operations involving frequent intersection, union and difference operations.

### Create Sets in NumPy
We can use NumPy's unique() method to find unique elements from any array. E.g. create a set array, but remember that the set arrays should only be 1-D arrays.

In [81]:
#Convert following array with repeated elements to a set:

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


### Finding Union

In [84]:
#Find union of the following two set arrays:

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


### Finding Intersection

In [87]:
#Find intersection of the following two set arrays:

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


__Note:__ the intersect1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.

### Finding Difference
To __find only the values in the first set that is NOT present in the seconds set__, use the setdiff1d() method.

In [88]:
#Find the difference of the set1 from set2:

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


### Finding Symmetric Difference
To find only the values that are NOT present in BOTH sets, use the setxor1d() method.

In [89]:
#Find the symmetric difference of the set1 and set2:

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
